In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
dataset = pd.read_csv('data_diabetes1.csv', sep=';')

In [25]:
X = dataset.iloc[:, :-1].values   # Semua kolom kecuali 'Outcome'
y = dataset.iloc[:, -1].values    # Hanya kolom 'Outcome'

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
print(X)

[[  nan  72.    nan  56.   20.8]
 [ 71.    nan   0.    0.   21.8]
 [ 74.   70.   40.   49.   35.3]
 [  nan  78.   30.    0.   27.6]
 [115.    nan   0.    0.   24. ]
 [124.   56.   13.  105.   21.8]
 [  nan  52.   10.   36.   27.8]
 [ 97.   64.   36.  100.   36.8]
 [120.    0.    0.    0.   30. ]
 [154.   78.   41.  140.   46.1]
 [144.   82.   40.    0.   41.3]
 [137.   70.   38.    0.   33.2]
 [119.   66.    nan   0.   38.8]
 [136.   90.    0.    0.   29.9]
 [114.   64.    0.    0.   28.9]
 [137.   84.   27.    0.   27.3]
 [105.   80.   45.  191.   33.7]
 [114.   76.   17.  110.   23.8]
 [126.   74.    nan  75.    nan]
 [132.   86.   31.    0.   28. ]]


In [28]:
#Menghilangkan missing value(NaN)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:5])
X[:, 0:5] = imputer.transform(X[:, 0:5])

In [29]:
print(X)

[[118.76470588  72.          21.64705882  56.          20.8       ]
 [ 71.          69.           0.           0.          21.8       ]
 [ 74.          70.          40.          49.          35.3       ]
 [118.76470588  78.          30.           0.          27.6       ]
 [115.          69.           0.           0.          24.        ]
 [124.          56.          13.         105.          21.8       ]
 [118.76470588  52.          10.          36.          27.8       ]
 [ 97.          64.          36.         100.          36.8       ]
 [120.           0.           0.           0.          30.        ]
 [154.          78.          41.         140.          46.1       ]
 [144.          82.          40.           0.          41.3       ]
 [137.          70.          38.           0.          33.2       ]
 [119.          66.          21.64705882   0.          38.8       ]
 [136.          90.           0.           0.          29.9       ]
 [114.          64.           0.           0.   

In [8]:
#membagi dataset ke dalam taining set dan test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
print(X_train)

[[144.          82.          40.           0.          41.3       ]
 [114.          76.          17.         110.          23.8       ]
 [118.76470588  52.          10.          36.          27.8       ]
 [136.          90.           0.           0.          29.9       ]
 [115.          69.           0.           0.          24.        ]
 [ 74.          70.          40.          49.          35.3       ]
 [124.          56.          13.         105.          21.8       ]
 [114.          64.           0.           0.          28.9       ]
 [154.          78.          41.         140.          46.1       ]
 [ 97.          64.          36.         100.          36.8       ]
 [105.          80.          45.         191.          33.7       ]
 [137.          70.          38.           0.          33.2       ]
 [118.76470588  78.          30.           0.          27.6       ]
 [118.76470588  72.          21.64705882  56.          20.8       ]
 [137.          84.          27.           0.   

In [10]:
print(X_test)

[[126.          74.          21.64705882  75.          30.36315789]
 [ 71.          69.           0.           0.          21.8       ]
 [132.          86.          31.           0.          28.        ]
 [120.           0.           0.           0.          30.        ]]


In [11]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]


In [12]:
print(y_test)

[0 0 0 1]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 0:] = sc.fit_transform(X_train[:, 0:])
X_test[:, 0:] = sc.fit_transform(X_test[:, 0:])

In [14]:
print(X_train)

[[ 1.26725801  1.02007075  1.0629105  -0.82173103  1.45627257]
 [-0.3432116   0.41182981 -0.44322044  1.01593938 -1.03460293]
 [-0.08743113 -2.02113397 -0.90160811 -0.22031162 -0.46525996]
 [ 0.83779945  1.83105868 -1.55644765 -0.82173103 -0.1663549 ]
 [-0.28952928 -0.29778463 -1.55644765 -0.82173103 -1.00613578]
 [-2.49050441 -0.19641114  1.0629105  -0.00313239  0.60225811]
 [ 0.1936116  -1.61564001 -0.70515625  0.93240891 -1.31927441]
 [-0.3432116  -0.80465208 -1.55644765 -0.82173103 -0.30869064]
 [ 1.80408121  0.61457679  1.12839445  1.51712222  2.13948413]
 [-1.25581104 -0.80465208  0.80097469  0.84887844  0.81576172]
 [-0.82635248  0.81732377  1.39033027  2.36913305  0.37452092]
 [ 0.89148177 -0.19641114  0.93194259 -0.82173103  0.30335305]
 [-0.08743113  0.61457679  0.40807096 -0.82173103 -0.49372711]
 [-0.08743113  0.00633584 -0.13891265  0.11381027 -1.46161016]
 [ 0.89148177  1.22281773  0.2116191  -0.82173103 -0.53642783]
 [-0.0748     -0.6019051  -0.13891265 -0.82173103  1.10

In [15]:
print(X_test)

[[ 0.56840145  0.49813094  0.62526094  1.73205081  0.82178847]
 [-1.70520435  0.34943514 -0.96985883 -0.57735027 -1.67154458]
 [ 0.81643117  0.85500086  1.31445671 -0.57735027  0.13370824]
 [ 0.32037173 -1.70256694 -0.96985883 -0.57735027  0.71604786]]


In [ ]:
#encoding data kategori (atribut) Matrix X yang terbentuk sebelumnya
#bertipe string, jadi perlu diubah ke numerik (int 
#atau float). karna saya sudah float tidak perlu kode berikut.
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [ ]:
#untuk mengubah yes or no menjadi 1 dan 0 
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#y = le.fit_transform(y)